name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly:"
          gofmt -s -l .
          exit 1
        fi

  docker:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        provenance: false
        build-args: |
          VERSION=${{ github.ref_name }}
          COMMIT=${{ github.sha }}
          DATE=${{ github.event.head_commit.timestamp }}

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          BINARY_NAME="flarecert-${{ matrix.os }}-${{ matrix.arch }}.exe"
        else
          BINARY_NAME="flarecert-${{ matrix.os }}-${{ matrix.arch }}"
        fi
        
        VERSION=${GITHUB_REF#refs/tags/}
        if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          VERSION="dev"
        fi
        
        go build -ldflags "-X github.com/bariiss/flarecert/cmd.version=$VERSION -X github.com/bariiss/flarecert/cmd.commit=${{ github.sha }} -X github.com/bariiss/flarecert/cmd.date=$(date -u '+%Y-%m-%d_%H:%M:%S')" -o "$BINARY_NAME" main.go
        
        # Create a unique directory for this artifact
        mkdir -p "dist/${{ matrix.os }}-${{ matrix.arch }}"
        mv "$BINARY_NAME" "dist/${{ matrix.os }}-${{ matrix.arch }}/"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: flarecert-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/${{ matrix.os }}-${{ matrix.arch }}/*
        retention-days: 7

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: flarecert-*
        merge-multiple: true
        path: ./release-artifacts
    
    - name: Get commit message
      id: commit
      run: |
        # Get the commit message for the tag
        COMMIT_MSG=$(git log -1 --pretty=format:"%s%n%n%b" ${{ github.sha }})
        echo "message<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Get short commit hash
        SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./release-artifacts/*
        generate_release_notes: true
        body: |
          ## 🚀 Release Notes
          
          ${{ steps.commit.outputs.message }}
          
          ---
          
          **Commit:** `${{ steps.commit.outputs.short_sha }}`  
          **Tag:** `${{ github.ref_name }}`  
          **Date:** `${{ github.event.head_commit.timestamp }}`
          
          ## 📥 Installation
          
          ### Homebrew (macOS)
          ```bash
          brew tap bariiss/flarecert
          brew install flarecert
          ```
          
          ### Go Install
          ```bash
          go install github.com/bariiss/flarecert@${{ github.ref_name }}
          ```
          
          ### Docker
          ```bash
          docker pull ghcr.io/bariiss/flarecert:${{ github.ref_name }}
          ```
          
          ### Binary Download
          Download the appropriate binary for your system:
          - **Linux (x64)**: `flarecert-linux-amd64`
          - **Linux (ARM64)**: `flarecert-linux-arm64`
          - **macOS (Intel)**: `flarecert-darwin-amd64`
          - **macOS (Apple Silicon)**: `flarecert-darwin-arm64`
          - **Windows (x64)**: `flarecert-windows-amd64.exe`
          
          Make the binary executable and move it to your PATH:
          ```bash
          chmod +x flarecert-*
          sudo mv flarecert-* /usr/local/bin/flarecert
          ```
          
          ## 🔧 Quick Start
          
          ```bash
          # Set up environment variables
          export CLOUDFLARE_API_TOKEN=your_token_here
          export CLOUDFLARE_EMAIL=your_email@example.com
          export ACME_EMAIL=your_email@example.com
          
          # List your Cloudflare zones
          flarecert zones
          
          # Generate a certificate (staging)
          flarecert cert --domain example.com --staging
          
          # Generate a wildcard certificate
          flarecert cert --domain "*.example.com"
          
          # Generate with Kubernetes Secret
          flarecert cert --domain example.com --k8s
          
          # List certificates
          flarecert list
          
          # Export existing certificates
          flarecert export --all
          
          # Renew certificates
          flarecert renew
          ```
          
          For detailed documentation, see the [README](https://github.com/bariiss/flarecert/blob/main/README.md).
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
